@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDQ2NDMwNTl9.ohU4-vf66yz8rOHwIabEeobafxZtdbW5m8HI4VJ2sxM
### Places Index
GET {{ domain }}/places

### Places Create
POST {{ domain }}/places
Content-Type: application/json

{
  "name": "A place to destroy later",
  "address": "Doesnt really matter now does it"
}

### Place Show
GET {{ domain }}/places/1

### Place Update
PATCH {{ domain }}/places/6
Content-Type: application/json

{
  "address": 6
}

### Place Destroy
DELETE {{ domain }}/places/6

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/places
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Test name",
  "address": "Test Address" 
}